apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
  labels:
    app: configmap-microservice-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: configmap-microservice-demo
